import math
print("Welcome to The Star Calculator!")
print("BY PRODA")
print("")
print("----------------------------------------------------------------------------")
print("")
dgA = int(input("Telescope in the first position's degrees [Yaw] [gº] --- "))
dgC = int(input("Telescope in the first position's degrees [Pich] [gº] --- "))
dgB = int(input("Telescope in the second position's degrees [Yaw] [gº] --- "))
zoom = int(input("Telescope's Zoom [Zx] --- "))
d = int(input("First and second position's distance [m] --- ")) / 9460730800000000
print("")
print("")
print("")
print("")
print("|\_/|\_/|\_/|")
print("=============")
print("|/-\|/-\|/-\|")
print("Distance")
print(str((math.sin(dgA * math.pi / 180) * (d / math.sin((180 - dgA - dgB) * math.pi / 180))) / math.sin(dgC * math.pi / 180)) + " light years [ly]")
print("|\_/|\_/|\_/|")
print("=============")
print("|/-\|/-\|/-\|")
print("Surface")
print(str((4 * math.pi * (2.5 * zoom) ** 2) * (math.sin(dgA * math.pi / 180) * (d / math.sin((180 - dgA - dgB) * math.pi / 180))) / math.sin(dgC * math.pi / 180) * 94607308000000000) + " scuare centimeters [cm^2]")
print("|\_/|\_/|\_/|")
print("=============")
print("|/-\|/-\|/-\|")
print("Volume")
print(str((1.333 * math.pi * (2.5 * zoom) ** 3) * (math.sin(dgA * math.pi / 180) * (d / math.sin((180 - dgA - dgB) * math.pi / 180))) / math.sin(dgC * math.pi / 180) * 94607308000000000) + " cubical centimeters [cm^3]")
print("|\_/|\_/|\_/|")
print("=============")
print("|/-\|/-\|/-\|")
print("Weight (helium)")
print(str((1100 * 1.333 * math.pi * (2.5 * zoom) ** 3 * 0.01) * (math.sin(dgA * math.pi / 180) * (d / math.sin((180 - dgA - dgB) * math.pi / 180))) / math.sin(dgC * math.pi / 180) * 94607308000000000) + " kilogram [kg]")
print("|\_/|\_/|\_/|")
print("")
print("")
while input("Write <Fn> to finish the program  ---  ") != "Fn":
    print("0_=")
